# Generated by Django 3.2.8 on 2021-12-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='busan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=30)),
                ('lat', models.FloatField(max_length=30)),
                ('lng', models.FloatField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('total', models.IntegerField(max_length=10)),
                ('y2018', models.IntegerField(max_length=8)),
                ('y2019', models.IntegerField(max_length=8)),
                ('y2020', models.IntegerField(max_length=8)),
                ('y2021', models.IntegerField(max_length=8)),
            ],
            options={
                'db_table': 'busan',
                'managed': False,
            },
        ),
    ]
