# Generated by Django 3.2.8 on 2021-12-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20211210_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=30)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('subject', models.CharField(max_length=30)),
                ('total', models.IntegerField()),
                ('y2018', models.IntegerField()),
                ('y2019', models.IntegerField()),
                ('y2020', models.IntegerField()),
                ('y2021', models.IntegerField()),
            ],
            options={
                'db_table': 'busan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chungbuk',
            fields=[
                ('place', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('y2018', models.IntegerField(blank=True, null=True)),
                ('y2019', models.IntegerField(blank=True, null=True)),
                ('y2020', models.IntegerField(blank=True, null=True)),
                ('y2021', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chungbuk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chungnam',
            fields=[
                ('place', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('y2018', models.IntegerField(blank=True, null=True)),
                ('y2019', models.IntegerField(blank=True, null=True)),
                ('y2020', models.IntegerField(blank=True, null=True)),
                ('y2021', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chungnam',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Daegu',
            fields=[
                ('place', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('y2018', models.IntegerField(blank=True, null=True)),
                ('y2019', models.IntegerField(blank=True, null=True)),
                ('y2020', models.IntegerField(blank=True, null=True)),
                ('y2021', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daegu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Daejeon',
            fields=[
                ('place', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('y2018', models.IntegerField(blank=True, null=True)),
                ('y2019', models.IntegerField(blank=True, null=True)),
                ('y2020', models.IntegerField(blank=True, null=True)),
                ('y2021', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daejeon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gangwon',
            fields=[
                ('place', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('y2018', models.IntegerField(blank=True, null=True)),
                ('y2019', models.IntegerField(blank=True, null=True)),
                ('y2020', models.IntegerField(blank=True, null=True)),
                ('y2021', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gangwon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gwangju',
            fields=[
                ('place', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('y2018', models.IntegerField(blank=True, null=True)),
                ('y2019', models.IntegerField(blank=True, null=True)),
                ('y2020', models.IntegerField(blank=True, null=True)),
                ('y2021', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gwangju',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gyeongbuk',
            fields=[
                ('place', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('y2018', models.IntegerField(blank=True, null=True)),
                ('y2019', models.IntegerField(blank=True, null=True)),
                ('y2020', models.IntegerField(blank=True, null=True)),
                ('y2021', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gyeongbuk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gyeonggi',
            fields=[
                ('place', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('y2018', models.IntegerField(blank=True, null=True)),
                ('y2019', models.IntegerField(blank=True, null=True)),
                ('y2020', models.IntegerField(blank=True, null=True)),
                ('y2021', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gyeonggi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gyeongnam',
            fields=[
                ('place', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('y2018', models.IntegerField(blank=True, null=True)),
                ('y2019', models.IntegerField(blank=True, null=True)),
                ('y2020', models.IntegerField(blank=True, null=True)),
                ('y2021', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gyeongnam',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incheon',
            fields=[
                ('place', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('y2018', models.IntegerField(blank=True, null=True)),
                ('y2019', models.IntegerField(blank=True, null=True)),
                ('y2020', models.IntegerField(blank=True, null=True)),
                ('y2021', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'incheon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jeju',
            fields=[
                ('place', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('y2018', models.IntegerField(blank=True, null=True)),
                ('y2019', models.IntegerField(blank=True, null=True)),
                ('y2020', models.IntegerField(blank=True, null=True)),
                ('y2021', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jeju',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jeonnam',
            fields=[
                ('place', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('y2018', models.IntegerField(blank=True, null=True)),
                ('y2019', models.IntegerField(blank=True, null=True)),
                ('y2020', models.IntegerField(blank=True, null=True)),
                ('y2021', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jeonnam',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sejong',
            fields=[
                ('place', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('y2018', models.IntegerField(blank=True, null=True)),
                ('y2019', models.IntegerField(blank=True, null=True)),
                ('y2020', models.IntegerField(blank=True, null=True)),
                ('y2021', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sejong',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seoul',
            fields=[
                ('place', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('y2018', models.IntegerField(blank=True, null=True)),
                ('y2019', models.IntegerField(blank=True, null=True)),
                ('y2020', models.IntegerField(blank=True, null=True)),
                ('y2021', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'seoul',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ulsan',
            fields=[
                ('place', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('y2018', models.IntegerField(blank=True, null=True)),
                ('y2019', models.IntegerField(blank=True, null=True)),
                ('y2020', models.IntegerField(blank=True, null=True)),
                ('y2021', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ulsan',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='MainpageBusan',
        ),
    ]
